# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
