# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='image',
            name='base64',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
