# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resolver', '0002_auto_20170622_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='base64',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
